### ISSUE TITLE
Without databinding and androidx conversion, app not working (gradle give error), please update in read.md file or documentation.

### ISSUE THREAD

**Issue by rajam1215** [manojbhadane/Holdy#5]
This error come please solve that issue. it is necessary.

ERROR: Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
is also present at [androidx.core:core:1.0.0-beta01] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
Suggestion: add 'tools:replace="android:appComponentFactory"' to element at AndroidManifest.xml:5:5-23:19 to override.

please enhance this library androidx to appcompact, because some of feature not work in androidx, and do proper documentation in git.

with androidx these lines also mandatory to add in gradle.properties
android.enableJetifier=true
android.useAndroidX=true

**Comment by rajam1215** [comment]
@manojbhadane 
Please update this documentation in .md file for library, if you do this stuff, it is so useful for the new developers. after that you can close this issue.

**Comment by manojbhadane** [comment]
Hi, document is already updated.

**Comment by rajam1215** [comment]
> Hi, document is already updated.

@manojbhadane
This is not updated in .md file, that you done in v1.6.1. this is such a awesome library. i appreciate that.

you remove this lines in .md file

Note
This library is using androidx, If you face any problems related to AppCompat library make sure you project is updated with androidx.

Download
This library is available in jitPack which is the default Maven repository used in Android Studio.
@@ -41,17 +37,6 @@ dependencies {
implementation 'com.github.manojbhadane:Holdy:v1.6.1'
}

**Step 3.** Enable databinding in your apps module **build.gradle**
```Gradle
android {
	 ...
	 
	dataBinding {
        	enabled true
    	}
}


please add those line in md file or make your project for appcompact

**Comment by manojbhadane** [comment]
Ok
